(function(g){var window=this;var Opa=function(a,b){return g.Tb(a,b)},D5=function(){},Ppa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.v(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Pb(a)},Qpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Hd&&"function"==typeof a.Hd)var c=a.Hd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.La(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Qb(a);d=Ppa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},E5=function(a){g.mn(a,"zx",g.ad());
return a},F5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.rn(a.l,b,c)},G5=function(a){return(a=g.Lo(a))?new ActiveXObject(a):new XMLHttpRequest},H5=function(a,b){return b+" ["+a.aa+" "+a.F+" "+a.getStatus()+"]"},Rpa=function(a){return"content-type"==a.toLowerCase()},I5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},Spa=function(a){return g.Ld&&g.md(9)&&g.Ea(a.timeout)&&g.Ca(a.ontimeout)},J5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},K5=function(a,b){if(a.g){I5(a);
var c=a.g,d=a.P[0]?g.Ga:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},L5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;J5(a);K5(a)},M5=function(a){return a.g?a.g.readyState:0},N5=function(a){if(a.i&&"undefined"!=typeof g.CY)if(a.P[1]&&4==M5(a)&&2==a.getStatus())H5(a,"Local request error detected and ignored");
else if(a.D&&4==M5(a))g.Ig(a.hw,0,a);else if(a.dispatchEvent("readystatechange"),4==M5(a)){H5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Tpa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<M5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";J5(a)}}finally{K5(a)}}},O5=function(a){g.Sf.call(this);
this.headers=new g.an;this.M=a||null;this.i=!1;this.P=this.g=null;this.aa=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.B=null;this.Z="";this.I=this.R=!1},P5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Upa=function(a,b){var c=[];
g.Wk(b,function(d){try{var e=g.$o.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.Zo(e)&&c.push(d):c.push(d)},a);
return c},Vpa=function(a,b){var c=Upa(a,b);
(0,g.B)(c,function(d){g.$o.prototype.remove.call(this,d)},a)},Q5=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},Wpa=function(a,b){g.$a(a,b)||a.push(b)},R5=function(a){var b=0,c;
for(c in a)b++;return b},S5=function(a,b){var c=b instanceof g.wc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.xc(c)},Xpa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},Ypa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(Xpa(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Zpa=function(a,b,c,d){var e=new g.dn(null,void 0);
a&&g.en(e,a);b&&g.fn(e,b);c&&g.gn(e,c);d&&(e.i=d);return e},T5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return Ypa(a)},U5=function(){this.g=[];
this.i=[]},V5=function(a,b){g.eq[a]=!0;
var c=g.cq();c&&c.publish.apply(c,arguments);g.eq[a]=!1},W5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.an;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",$pa(this,a.capabilities||""),aqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},$pa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(Opa,bqa)).forEach(function(c){a.capabilities.add(c)})},aqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},X5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},Y5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Z5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},cqa=function(a){return new X5(a)},$5=function(a){return g.Ka(a)?(0,g.G)(a,cqa):[]},a6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},b6=function(a){return g.Ka(a)?"["+(0,g.G)(a,a6).join(",")+"]":"null"},c6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},dqa=function(a){return(0,g.G)(a,function(b){return{key:b.id,
name:b.name}})},d6=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},e6=function(a,b){return g.Xa(a,function(c){return Y5(c,b)})},eqa=function(){var a=(0,g.vt)();
a&&Vpa(a,a.g.hf(!0))},f6=function(){var a=g.zt("yt-remote-connected-devices")||[];
g.pb(a);return a},fqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(d,e){return 0==e?d:d.substring(c.length)})},g6=function(a){g.xt("yt-remote-connected-devices",a,86400)},i6=function(){if(h6)return h6;
var a=g.zt("yt-remote-device-id");a||(a=c6(),g.xt("yt-remote-device-id",a,31536E3));for(var b=f6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return h6=d},j6=function(){var a=f6(),b=i6();
g.$a(a,b);g.Bt()&&g.rb(a,b);a=fqa(a);if(0==a.length)try{g.Cs("remote_sid")}catch(c){}else try{g.Bs("remote_sid",a.join(","),-1)}catch(c){}},k6=function(){return g.zt("yt-remote-session-browser-channel")},l6=function(){return g.zt("yt-remote-local-screens")||[]},m6=function(){g.xt("yt-remote-lounge-token-expiration",!0,86400)},gqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(l6(),function(d){return d.loungeToken}),c=(0,g.G)(a,function(d){return d.loungeToken});
(0,g.lj)(c,function(d){return!g.$a(b,d)})&&m6();
g.xt("yt-remote-local-screens",a,31536E3)},hqa=function(a,b){g.xt("yt-remote-session-browser-channel",a);
g.xt("yt-remote-session-screen-id",b);var c=f6(),d=i6();g.$a(c,d)||c.push(d);g6(c);j6()},n6=function(a){a||(g.At("yt-remote-session-screen-id"),g.At("yt-remote-session-video-id"));
j6();a=f6();g.cb(a,i6());g6(a)},p6=function(){if(!o6){var a=g.jp();
a&&(o6=new g.Uo(a))}return o6?!!o6.get("yt-remote-use-staging-server"):!1},q6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},r6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?s6(a.shift(),function(){t6(a)}):u6()},iqa=function(a){return"chrome-extension://"+a+v6},s6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=r6();
a&&a(!1,"No cast extension found")},w6=function(){if(jqa){var a=2,b=r6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;s6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},kqa=function(){w6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+v6,"//www.gstatic.com/eureka/clank"+v6])},x6=function(a,b,c){g.H.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Vc=b;this.u=(0,g.y)(this.bD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},y6=function(){},z6=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ba=new g.sn(this);this.i=new g.Hg;this.i.setInterval(250)},B6=function(a,b,c){a.ai=1;
a.jg=E5(b.clone());a.sh=c;a.u=!0;A6(a,null)},C6=function(a,b,c,d,e){a.ai=1;
a.jg=E5(b.clone());a.sh=null;a.u=c;e&&(a.Zz=!1);A6(a,d)},A6=function(a,b){a.Ei=(0,g.D)();
D6(a);a.Bg=a.jg.clone();F5(a.Bg,"t",a.A);a.Xk=0;a.tc=a.g.tp(a.g.Nk()?b:null);0<a.Xp&&(a.zn=new g.Ml((0,g.y)(a.fB,a,a.tc),a.Xp));a.ba.da(a.tc,"readystatechange",a.IL);var c=a.Xg?g.ac(a.Xg):{};a.sh?(a.ho="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Bg,a.ho,a.sh,c)):(a.ho="GET",a.Zz&&!g.Nd&&(c.Connection="close"),a.tc.send(a.Bg,a.ho,null,c));a.g.re(1)},K6=function(a,b,c){for(var d=!0;!a.Ng&&a.Xk<c.length;){var e=lqa(a,c);
if(e==E6){4==b&&(a.kg=4,F6(15),d=!1);break}else if(e==G6){a.kg=4;F6(16);d=!1;break}else H6(a,e)}4==b&&0==c.length&&(a.kg=1,F6(17),d=!1);a.xe=a.xe&&d;d||(I6(a),J6(a))},lqa=function(a,b){var c=a.Xk,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return G6;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.Xk=d+c;return e},N6=function(a,b){a.Ei=(0,g.D)();
D6(a);var c=b?window.location.hostname:"";a.Bg=a.jg.clone();g.mn(a.Bg,"DOMAIN",c);g.mn(a.Bg,"t",a.A);try{a.Be=new ActiveXObject("htmlfile")}catch(n){I6(a);a.kg=7;F6(22);J6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in L6)k=L6[l];else if(l in M6)k=L6[l]=M6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
L6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Qc(g.pc("b/12014412"),d+"</body></html>");a.Be.open();a.Be.write(g.Lc(c));a.Be.close();a.Be.parentWindow.m=(0,g.y)(a.dL,a);a.Be.parentWindow.d=(0,g.y)(a.fz,a,!0);a.Be.parentWindow.rpcClose=(0,g.y)(a.fz,a,!1);c=a.Be.createElement("DIV");a.Be.parentWindow.document.body.appendChild(c);d=g.Bc(a.Bg.toString());d=g.Xc(g.yc(d));d=g.Qc(g.pc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Rc(c,d);a.g.re(1)},D6=function(a){a.kt=(0,g.D)()+a.o;
O6(a,a.o)},O6=function(a,b){if(null!=a.Ui)throw Error("WatchDog timer not null");
a.Ui=P6((0,g.y)(a.nL,a),b)},Q6=function(a){a.Ui&&(g.w.clearTimeout(a.Ui),a.Ui=null)},J6=function(a){a.g.ew()||a.Ng||a.g.jn(a)},I6=function(a){Q6(a);
g.pf(a.zn);a.zn=null;a.i.stop();g.un(a.ba);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Be&&(a.Be=null)},H6=function(a,b){try{a.g.Zy(a,b),a.g.re(4)}catch(c){}},S6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;R6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){S6(a,b,c,d,f)},f)})}},R6=function(a,b,c){var d=new Image;
d.onload=function(){try{T6(d),c(!0)}catch(e){}};
d.onerror=function(){try{T6(d),c(!1)}catch(e){}};
d.onabort=function(){try{T6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{T6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
S5(d,a)},T6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},U6=function(a){this.g=a;
this.i=new y6},W6=function(a){var b=V6(a.g,a.ej,"/mail/images/cleardot.gif");
E5(b);S6(b.toString(),5E3,(0,g.y)(a.mC,a),3,2E3);a.re(1)},Y6=function(a){var b=a.g.F;
if(null!=b)F6(5),b?(F6(11),X6(a.g,a,!1)):(F6(12),X6(a.g,a,!0));else if(a.Dd=new z6(a,void 0,void 0,void 0),a.Dd.Xg=a.Vp,b=a.g,b=V6(b,b.Nk()?a.Jj:null,a.Wp),F6(5),!g.Ld||g.nd(10))F5(b,"TYPE","xmlhttp"),C6(a.Dd,b,!1,a.Jj,!1);else{F5(b,"TYPE","html");var c=a.Dd;a=!!a.Jj;c.ai=3;c.jg=E5(b.clone());N6(c,a)}},Z6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new y6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},mqa=function(a,b){this.g=a;
this.map=b;this.context=null},$6=function(a){g.rf.call(this,"statevent",a)},a7=function(a,b){g.rf.call(this,"timingevent",a);
this.size=b},b7=function(a){g.rf.call(this,"serverreachability",a)},f7=function(a){c7(a);
if(3==a.g){var b=a.uk++,c=a.Wl.clone();g.mn(c,"SID",a.l);g.mn(c,"RID",b);g.mn(c,"TYPE","terminate");d7(a,c);b=new z6(a,a.l,b,void 0);b.ai=2;b.jg=E5(c.clone());S5(new Image,b.jg.toString());b.Ei=(0,g.D)();D6(b)}e7(a)},h7=function(a){a.CC(1,0);
a.Wl=V6(a,null,a.Up);g7(a)},c7=function(a){a.Zf&&(a.Zf.abort(),a.Zf=null);
a.Qb&&(a.Qb.cancel(),a.Qb=null);a.kf&&(g.w.clearTimeout(a.kf),a.kf=null);i7(a);a.zd&&(a.zd.cancel(),a.zd=null);a.fg&&(g.w.clearTimeout(a.fg),a.fg=null)},j7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new mqa(a.nH++,b));2!=a.g&&3!=a.g||g7(a)},g7=function(a){a.zd||a.fg||(a.fg=P6((0,g.y)(a.ez,a),0),a.Uh=0)},m7=function(a,b){if(1==a.g){if(!b){a.uk=Math.floor(1E5*Math.random());
var c=a.uk++,d=new z6(a,"",c,void 0);d.Xg=null;var e=k7(a),f=a.Wl.clone();g.mn(f,"RID",c);g.mn(f,"CVER","1");d7(a,f);B6(d,f,e);a.zd=d;a.g=2}}else 3==a.g&&(b?l7(a,b):0==a.i.length||a.zd||l7(a))},l7=function(a,b){if(b)if(6<a.Og){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.uk-1;var d=k7(a)}else c=b.B,d=b.sh;else c=a.uk++,d=k7(a);var e=a.Wl.clone();g.mn(e,"SID",a.l);g.mn(e,"RID",c);g.mn(e,"AID",a.ki);d7(a,e);c=new z6(a,a.l,c,a.Uh+1);c.Xg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.zd=c;B6(c,e,d)},d7=function(a,b){if(a.Tc){var c=a.Tc.Iv();
c&&g.Jb(c,function(d,e){g.mn(b,e,d)})}},k7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Og&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Og?e:f-d;try{g.Jb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},n7=function(a){a.Qb||a.kf||(a.B=1,a.kf=P6((0,g.y)(a.dz,a),0),a.Nh=0)},p7=function(a){if(a.Qb||a.kf||3<=a.Nh)return!1;
a.B++;a.kf=P6((0,g.y)(a.dz,a),o7(a,a.Nh));a.Nh++;return!0},X6=function(a,b,c){a.eo=c;
a.Je=b.xf;a.A||h7(a)},i7=function(a){null!=a.Sg&&(g.w.clearTimeout(a.Sg),a.Sg=null)},o7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},r7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.y)(a.mM,a);c||(c=new g.dn("//www.google.com/images/cleardot.gif"),E5(c));R6(c.toString(),1E4,d)}else F6(2);q7(a,b)},q7=function(a,b){a.g=0;
a.Tc&&a.Tc.Gu(b);e7(a);c7(a)},e7=function(a){a.g=0;
a.Je=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.gp();else{g.fb(a.o);var b=g.fb(a.i);a.o.length=0;a.i.length=0;a.Tc.gp(b)}},V6=function(a,b,c){var d=g.nn(c);
if(""!=d.g)b&&g.fn(d,b+"."+d.g),g.gn(d,d.u);else{var e=window.location;d=Zpa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.rj&&g.Jb(a.rj,function(f,k){g.mn(d,k,f)});
g.mn(d,"VER",a.Og);d7(a,d);return d},P6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},F6=function(a){s7.dispatchEvent(new $6(s7,a))},t7=function(){},nqa=function(a,b){this.action=a;
this.params=b||{}},u7=function(a,b){g.H.call(this);
this.g=new g.N(this.VK,0,this);g.I(this,this.g);this.Vc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},v7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.To;this.i=new u7(this.RL,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},oqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.eo,sessionId:a.g.l,arrayId:a.g.ki}},w7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&m7(a.g),f7(a.g));a.D=0},x7=function(a){return!!a.g&&3==a.g.g},pqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},y7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Vg(a)||"";b&&(this.port=":"+b);this.domain=g.Ug(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Gb(a,"10.0")&&(this.i=!1))},z7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.dh(c+b,{})},A7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),qd:g.Qa(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Xq(b,a)},qqa=function(){var a=B7;
C7();D7.push(a);E7(D7)},F7=function(a,b){C7();
var c=D7,d=rqa(a,String(b));0==c.length?sqa(d):(E7(c),(0,g.B)(c,function(e){e(d)}))},C7=function(){D7||(D7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",D7,void 0))},sqa=function(a){var b=(G7+1)%50;
G7=b;H7[b]=a;I7||(I7=49==b)},E7=function(a){var b=H7;
if(b[0]){var c=G7,d=I7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
H7=Array(50);G7=-1;I7=!1}},rqa=function(a,b){var c=((0,g.D)()-tqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},J7=function(a){g.Q.call(this);
this.B=a;this.g=[]},uqa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},vqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!d6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=uqa(a,b[d])||c;return c},wqa=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},K7=function(a,b,c,d){g.Q.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},M7=function(a){J7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;L7(this);this.info("Initializing with "+b6(this.g))},xqa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(d){return d.id}),c=z7(a.l,"/pairing/get_lounge_token_batch");
A7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.lD,a),(0,g.y)(a.kD,a))}},L7=function(a){var b=$5(l6());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return vqa(a,b)},N7=function(a,b){gqa((0,g.G)(a.g,Z5));
b&&m6()},P7=function(a,b){g.Q.call(this);
this.A=b;var c=g.zt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;O7("Initialized with "+g.Mg(this.g))},yqa=function(a,b,c){var d=z7(a.u,"/pairing/get_screen_availability");
A7(a.u,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},Q7=function(a,b){a:if(R5(b)!=R5(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(O7("Updated online screens: "+g.Mg(a.g)),a.g=b,a.N("screenChange"));zqa(a)},R7=function(a){isNaN(a.l)||g.bq(a.l);
a.l=g.$p((0,g.y)(a.ks,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},O7=function(a){F7("OnlineScreenService",a)},Aqa=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},zqa=function(a){a=g.Qb(g.Kb(a.g,function(b){return b}));
g.pb(a);a.length?g.xt("yt-remote-online-screen-ids",a.join(","),60):g.At("yt-remote-online-screen-ids")},S7=function(a){J7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Bqa(this)},Dqa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Jd();if(k=(c?e6(k,c):null)||e6(k,b)){k.uuid=b;var l=T7(a,k);yqa(a.i,l,function(m){e(m?l:null)})}else c?Cqa(a,c,(0,g.y)(function(m){var n=T7(this,new X5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));yqa(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},Eqa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Cqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Xq(z7(a.A,"/pairing/get_lounge_token_batch"),e)},Fqa=function(a){a.g=a.l.Jd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+b6(a.g))},Bqa=function(a){U7(a);
a.l=new M7(a.A);a.l.subscribe("screenChange",(0,g.y)(a.uD,a));Fqa(a);a.o=$5(g.zt("yt-remote-automatic-screen-cache")||[]);U7(a);a.info("Initializing automatic screens: "+b6(a.o));a.i=new P7(a.A,(0,g.y)(a.Jd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.N("onlineScreenChange")},a))},T7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=e6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.xt("yt-remote-automatic-screen-cache",(0,g.G)(a.o,Z5)));U7(a);a.u[b.uuid]=b.id;g.xt("yt-remote-device-id-map",a.u,31536E3);return b},U7=function(a){a.u=g.zt("yt-remote-device-id-map")||{}},V7=function(a,b,c){g.Q.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},W7=function(a,b){F7(a.P,b)},X7=function(a,b){V7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.OM,this);this.u=(0,g.y)(this.yL,this);this.o=g.$p((0,g.y)(function(){Gqa(this,null)},this),12E4)},Hqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Mg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ga,(0,g.y)(function(){W7(this,"Failed to send message: getMdxSessionStatus.")},a)):W7(a,"Sending yt message without session: "+g.Mg(b))},Gqa=function(a,b){g.bq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.kn,a),d=(0,g.y)(a.Md,a);a.Xv(b,c,d,5)}}else a.Md(Error("Waiting for session status timed out."))},Y7=function(a,b,c){V7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ga;this.A=NaN;this.I=(0,g.y)(this.RM,this);this.g=g.Ga},Iqa=function(a){a.g=a.F.kB(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ga;
this.kn(b)},a),(0,g.y)(function(b){this.g=g.Ga;
this.Md(b)},a))},Jqa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}p6()&&(b.env_useStageMdx=1);return g.bh(b)},Z7=function(a,b){V7.call(this,a,b,"ManualSession");
this.g=g.$p((0,g.y)(this.mi,this,null),150)},$7=function(a,b,c,d){g.Q.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.eK,this)},Kqa=function(a,b){return b?g.Xa(a.l,function(c){return Y5(b,c.label)},a):null},a8=function(a){F7("Controller",a)},B7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},b8=function(a){return a.u||!!a.l.length||!!a.g},c8=function(a,b,c){b!=a.g&&(g.pf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.cz,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.mi(null)):a.N("yt-remote-cast2-session-change",null))},Lqa=function(a){var b=a.i.jB(),c=a.g&&a.g.i;
a=(0,g.G)(b,function(d){c&&Y5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Kqa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Rqa=function(a,b,c,d,e,f,k){Mqa()?Nqa(b,e,f,k)&&(e8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Oqa(a,c):(window.__onGCastApiAvailable=function(l,m){l?Oqa(a,c):(f8("Failed to load cast API: "+m),g8(!1),e8(!1),g.At("yt-remote-cast-available"),g.At("yt-remote-cast-receiver"),Pqa(),c(!1))},d?g.mq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?kqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(w6(),t6(Qqa.map(iqa))))):d8("Cannot initialize because not running Chrome")},Pqa=function(){d8("dispose");
var a=h8();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);Sqa(!1);g.hq(i8);i8.length=0},j8=function(){return!!g.zt("yt-remote-cast-installed")},Tqa=function(){var a=g.zt("yt-remote-cast-receiver");
return a?a.friendlyName:null},Uqa=function(){d8("clearCurrentReceiver");
g.At("yt-remote-cast-receiver")},Vqa=function(){return j8()?h8()?h8().getCastSession():(f8("getCastSelector: Cast is not initialized."),null):(f8("getCastSelector: Cast API is not installed!"),null)},l8=function(){j8()?h8()?k8()?(d8("Requesting cast selector."),h8().requestSession()):(d8("Wait for cast API to be ready to request the session."),i8.push(g.gq("yt-remote-cast2-api-ready",l8))):f8("requestCastSelector: Cast is not initialized."):f8("requestCastSelector: Cast API is not installed!")},m8=
function(a,b){k8()?h8().setConnectedScreenStatus(a,b):f8("setConnectedScreenStatus called before ready.")},Mqa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.fx||a},Wqa=function(a,b){h8().init(a,b)},Nqa=function(a,b,c,d){var e=!1;
h8()||(a=new $7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.xt("yt-remote-cast-available",f);V5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){d8("onReceiverSelected: "+f.friendlyName);
g.xt("yt-remote-cast-receiver",f);V5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){d8("onReceiverResumed: "+f.friendlyName);
g.xt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){d8("onSessionChange: "+a6(f));
f||g.At("yt-remote-cast-receiver");V5("yt-remote-cast2-session-change",f)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
d8("cloudview.createSingleton_: "+e);return e},h8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Oqa=function(a,b){g8(!0);
e8(!1);Wqa(a,function(c){c?(Sqa(!0),g.jq("yt-remote-cast2-api-ready")):(f8("Failed to initialize cast API."),g8(!1),g.At("yt-remote-cast-available"),g.At("yt-remote-cast-receiver"),Pqa());b(c)})},d8=function(a){F7("cloudview",a)},f8=function(a){F7("cloudview",a)},g8=function(a){d8("setCastInstalled_ "+a);
g.xt("yt-remote-cast-installed",a)},k8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Sqa=function(a){d8("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},e8=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},n8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Le=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},o8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Le=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},p8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},q8=function(a,b){a.B=b;
a.A=(0,g.D)()},r8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},s8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&o8(a)},t8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.g);b.hasPrevious=a.Le;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},v8=function(a,b){g.Q.call(this);
this.g=0;this.o=a;this.A=[];this.u=new U5;this.l=this.i=null;this.F=(0,g.y)(this.XH,this);this.B=(0,g.y)(this.xk,this);this.D=(0,g.y)(this.WH,this);this.H=(0,g.y)(this.jI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.nt,this),Xqa(this))):c=3;0!=c&&(b?this.nt(c):g.$p((0,g.y)(function(){this.nt(c)},this),0));
var d=Vqa();d&&u8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},w8=function(a){return new n8(a.o.getPlayerContextData())},Xqa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.bK,b),this))},a)},Yqa=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},x8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},z8=function(a,b,c){var d=w8(a);
q8(d,c);-1E3!=d.playerState&&(d.playerState=b);y8(a,d)},A8=function(a,b,c){a.o.sendMessage(b,c)},y8=function(a,b){Yqa(a);
a.o.setPlayerContextData(t8(b));Xqa(a)},u8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.xk(null));
a.l=b;a.l&&(F7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.xk(a.l.media[0]))},Zqa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=w8(a);b.contentId!=d.videoId&&F7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;q8(d,a.i.getEstimatedTime());y8(a,d)}else F7("CP","No cast media video. Ignoring state update.")},B8=function(a,b,c){return(0,g.y)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),A8(this,b,c))},a)},C8=function(a,b,c){g.Q.call(this);
this.u=NaN;this.M=!1;this.H=this.F=this.I=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Pa=this.g=null;this.na=a;this.O.push(g.ds(window,"beforeunload",(0,g.y)(this.eD,this)));this.i=[];this.Pa=new n8;this.V=b.id;this.g=$qa(this,c);this.g.subscribe("handlerOpened",this.bI,this);this.g.subscribe("handlerClosed",this.YH,this);this.g.subscribe("handlerError",this.ZH,this);this.g.subscribe("handlerMessage",this.aI,this);pqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Pa.videoId;
g.Bt()&&g.xt("yt-remote-session-video-id",d)},this)},D8=function(a){F7("conn",a)},$qa=function(a,b){return new v7(z7(a.na,"/bc"),b)},E8=function(a,b){a.N("proxyStateChange",b)},ara=function(a){a.u=g.$p((0,g.y)(function(){D8("Connecting timeout");
this.A(1)},a),2E4)},F8=function(a){g.bq(a.u);
a.u=NaN},G8=function(a){g.bq(a.P);
a.P=NaN},bra=function(a){H8(a);
a.I=g.$p((0,g.y)(function(){I8(this,"getNowPlaying")},a),2E4)},H8=function(a){g.bq(a.I);
a.I=NaN},dra=function(a,b){b&&(F8(a),G8(a));
b==(x7(a.g)&&isNaN(a.u))?b&&(E8(a,1),I8(a,"getSubtitlesTrack")):b?(a.R()&&a.Pa.reset(),E8(a,1),I8(a,"getNowPlaying"),cra(a)):a.A(1)},era=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.Wb(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.N("remotePlayerChange"))},fra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;s8(a.Pa,c,d);a.N("remoteQueueChange")},hra=function(a,b){b.params=b.params||{};
fra(a,b);gra(a,b);a.N("autoplayDismissed")},gra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
q8(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?bra(a):H8(a);a.N("remotePlayerChange")},ira=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);q8(a.Pa,isNaN(c)?0:c);a.N("remotePlayerChange")}},jra=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.N("remotePlayerChange")},kra=function(a,b){a.B=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},lra=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Le="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.N("previousNextChange")},cra=function(a){g.bq(a.H);
a.H=g.$p((0,g.y)(a.A,a,1),864E5)},I8=function(a,b,c){c?D8("Sending: action="+b+", params="+g.Mg(c)):D8("Sending: action="+b);
a.g.sendMessage(b,c)},J8=function(a){J7.call(this,"ScreenServiceProxy");
this.Hc=a;this.i=[];this.i.push(this.Hc.$_s("screenChange",(0,g.y)(this.LM,this)));this.i.push(this.Hc.$_s("onlineScreenChange",(0,g.y)(this.FJ,this)))},qra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Sp("MDX_CONFIG")||b;eqa();j6();K8||(K8=new y7(b?b.loungeApiHost:void 0),p6()&&(K8.g="/api/loungedev"));L8||(L8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",L8,void 0));mra();var c=M8();if(!c){var d=new S7(K8);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=M8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Rqa(a,d,function(m){m?N8()&&m8(N8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){V5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),O8("Initializing: "+g.Mg(b)),P8.push(g.gq("yt-remote-cast2-availability-change",function(){V5("yt-remote-receiver-availability-change")})),P8.push(g.gq("yt-remote-cast2-receiver-selected",function(){Q8(null);
V5("yt-remote-auto-connect","cast-selector-receiver")})),P8.push(g.gq("yt-remote-cast2-receiver-resumed",function(){V5("yt-remote-receiver-resumed","cast-selector-receiver")})),P8.push(g.gq("yt-remote-cast2-session-change",nra)),P8.push(g.gq("yt-remote-connection-change",function(m){m?m8(N8(),"YouTube TV"):R8()||(m8(null,null),Uqa())})),a=S8(),b.isAuto&&(a.id+="#dial"),g.Oq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),O8(" -- with channel params: "+
g.Mg(a)),ora(a),c.start(),N8()||pra())},sra=function(){var a=rra();
j8()&&g.zt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},rra=function(){var a=M8().Hc.$_gos();
var b=T8();b&&U8()&&(d6(a,b)||a.push(b));return dqa(a)},V8=function(){var a=tra();
!a&&j8()&&Tqa()&&(a={key:"cast-selector-receiver",name:Tqa()});return a},tra=function(){var a=rra(),b=T8();
b||(b=R8());return g.Xa(a,function(c){return b&&Y5(b,c.key)?!0:!1})},T8=function(){var a=N8();
if(!a)return null;var b=M8().Jd();return e6(b,a)},nra=function(a){O8("remote.onCastSessionChange_: "+a6(a));
if(a){var b=T8();b&&b.id==a.id?m8(b.id,"YouTube TV"):(b&&W8(),X8(a,1))}else U8()&&W8()},W8=function(){k8()?h8().stopSession():f8("stopSession called before API ready.");
var a=U8();a&&(a.disconnect(1),Y8(null))},Z8=function(){var a=U8();
return!!a&&3!=a.getProxyState()},O8=function(a){F7("remote",a)},M8=function(){if(!$8){var a=g.x("yt.mdx.remote.screenService_");
$8=a?new J8(a):null}return $8},N8=function(){return g.x("yt.mdx.remote.currentScreenId_")},ura=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},vra=function(){return g.x("yt.mdx.remote.connectData_")},Q8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},U8=function(){return g.x("yt.mdx.remote.connection_")},Y8=function(a){var b=U8();
Q8(null);a||ura("");g.Fa("yt.mdx.remote.connection_",a,void 0);L8&&((0,g.B)(L8,function(c){c(a)}),L8.length=0);
b&&!a?V5("yt-remote-connection-change",!1):!b&&a&&V5("yt-remote-connection-change",!0)},R8=function(){var a=g.Bt();
if(!a)return null;var b=M8().Jd();return e6(b,a)},X8=function(a,b){T8()&&T8();
ura(a.id);var c=new C8(K8,a,S8());c.connect(b,vra());c.subscribe("beforeDisconnect",function(d){V5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){U8()&&Y8(null)});
Y8(c)},pra=function(){var a=R8();
a?(O8("Resume connection to: "+a6(a)),X8(a,0)):(n6(),Uqa(),O8("Skipping connecting because no session screen found."))},mra=function(){var a=S8();
if(g.Wb(a)){a=i6();var b=g.zt("yt-remote-session-name")||"",c=g.zt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},S8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},ora=function(a){a?(g.xt("yt-remote-session-app",a.app),g.xt("yt-remote-session-name",a.name)):(g.At("yt-remote-session-app"),g.At("yt-remote-session-name"));
g.Fa("yt.mdx.remote.channelParams_",a,void 0)},a9=function(a,b,c){g.H.call(this);
this.u=a;this.i=b;this.l=new g.Ms(this);g.I(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.WI);this.l.K(b,"captionschanged",this.VH);this.l.K(b,"captionssettingschanged",this.yA);this.l.K(b,"videoplayerreset",this.ln);this.l.K(b,"mdxautoplaycancel",this.lC);this.O=this.l.K(b,"onVolumeChange",this.Ny);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Yy,this);c.subscribe("remotePlayerChange",this.zk,this);c.subscribe("remoteQueueChange",this.ln,this);c.subscribe("autoplayUpNext",this.Cy,
this);c.subscribe("previousNextChange",this.Vy,this);c.subscribe("nowAutoplaying",this.Ry,this);c.subscribe("autoplayDismissed",this.By,this);this.suggestion=null;this.F=new g.AC(64);this.o=new g.N(this.wA,500,this);g.I(this,this.o);this.A=new g.N(this.xA,1E3,this);g.I(this,this.A);this.I=new x6(this.vM,0,this);g.I(this,this.I);this.B={};this.P=new g.N(this.WA,1E3,this);g.I(this,this.P);this.H=new g.Ml(this.BF,1E3,this);g.I(this,this.H);this.M=g.Ga;this.yA();this.ln();this.zk()},b9=function(a,b){a.u.rd(b,
a.i.getVideoData().lengthSeconds)},wra=function(a){b9(a,0);
a.o.stop();c9(a,new g.AC(64))},e9=function(a,b){if(d9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.dc(c,b));a.g.mA(a.i.getVideoData(1).videoId,c);a.B=w8(a.g).g}},f9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.zf,Q5(c));c9(a,new g.AC(1))},xra=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{gQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},d9=function(a){return w8(a.g).videoId==a.i.getVideoData(1).videoId},c9=function(a,b){a.A.stop();
var c=a.F;if(!g.GC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.tK(a.i,d);a.F=b;yra(a.u,c,b)}},g9=function(a){g.W.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.FP()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.pQ(this,250);g.I(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);zra(this,g.pK(a))},zra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.DN("L\u1ed7i tr\u00ean $RECEIVER_NAME",c):g.HC(b)||g.U(b,4)?g.DN("\u0110ang ph\u00e1t tr\u00ean $RECEIVER_NAME",c):g.DN("\u0110\u01b0\u1ee3c k\u1ebft n\u1ed1i v\u1edbi $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},h9=function(a,b){g.ZT.call(this,"Ph\u00e1t tr\u00ean",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},i9=function(a){g.TK.call(this,a);
this.i={key:c6(),name:"M\u00e1y t\u00ednh n\u00e0y"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.fk=new g.AC(64);this.D=0;this.Bm=-1;if(!g.lz(g.X(this.player))){a=this.player;var b=g.tD(a);b&&(b=b.hk())&&(b=new h9(a,b),g.I(this,b));b=new g9(a);g.I(this,b);g.FK(a,b.element,4)}},yra=function(a,b,c){a.fk=c;
a.player.N("presentingplayerstatechange",new g.HD(c,b))},j9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)W8();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.zf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=Q5(d))&&(c.locationInfo=d);d=c}else d=null;O8("Connecting to: "+g.Mg(b));"cast-selector-receiver"==b.key?
(Q8(d||null),k8()?h8().setLaunchParams(d||null):f8("setLaunchParams called before ready.")):!d&&Z8()&&N8()==b.key?V5("yt-remote-connection-change",!0):(W8(),Q8(d||null),d=M8().Jd(),(d=e6(d,b.key))&&X8(d,1))}},Tpa=/^https?$/i,Ara=["POST",
"PUT"];g.A(O5,g.Sf);g.h=O5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.aa=b;this.O=!1;this.i=!0;this.g=this.M?G5(this.M):G5(g.YY);this.P=this.M?this.M.getOptions():g.YY.getOptions();this.g.onreadystatechange=(0,g.y)(this.hw,this);try{D5(H5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){D5(H5(this,"Error opening Xhr: "+f.message));L5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Qpa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Hd(),Rpa);c=g.w.FormData&&a instanceof g.w.FormData;!g.$a(Ara,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{I5(this),0<this.A&&(this.I=Spa(this.g),D5(H5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.iw,this)):this.B=g.Ig(this.iw,this.A,this)),D5(H5(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){D5(H5(this,"Send error: "+f.message)),L5(this,f)}};
g.h.iw=function(){"undefined"!=typeof g.CY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,H5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(H5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),K5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),K5(this,!0));O5.Ha.T.call(this)};
g.h.hw=function(){this.ea()||(this.V||this.D||this.o?N5(this):this.dK())};
g.h.dK=function(){N5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<M5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var M6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},L6={"'":"\\'"},Bra={};g.h=U5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Dma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var bqa={kN:"atp",uP:"ska",jP:"que",JO:"mus",tP:"sus",aO:"dsp",qP:"seq"};W5.prototype.ag=function(){var a=new W5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var o6,h6="",v6=q6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",jqa=q6("loadCastFramework")||q6("loadCastApplicationFramework"),Qqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(x6,g.H);g.h=x6.prototype;g.h.aD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.D)()+this.Vc:this.za=g.Ig(this.u,this.Vc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();x6.Ha.T.call(this)};
g.h.bD=function(){this.l?(this.za=g.Ig(this.u,this.l-(0,g.D)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};y6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Xg=null;g.h.xe=!1;g.h.Ui=null;g.h.kt=null;g.h.Ei=null;g.h.ai=null;g.h.jg=null;g.h.Bg=null;g.h.sh=null;g.h.tc=null;g.h.Xk=0;g.h.Be=null;g.h.ho=null;g.h.kg=null;g.h.Kj=-1;g.h.Zz=!0;g.h.Ng=!1;g.h.Xp=0;g.h.zn=null;var G6={},E6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.IL=function(a){a=a.target;var b=this.zn;b&&3==M5(a)?b.Gj():this.fB(a)};
g.h.fB=function(a){try{if(a==this.tc)a:{var b=M5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Ld&&!g.nd(10)||g.Nd&&!g.md("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Dh&&!P5(this.tc))break a;this.Ng||4!=b||7==c||(8==c||0>=d?this.g.re(3):this.g.re(2));Q6(this);var e=this.tc.getStatus();this.Kj=e;var f=P5(this.tc);(this.xe=200==e)?(4==b&&I6(this),this.u?(K6(this,b,f),g.Dh&&this.xe&&3==b&&(this.ba.da(this.i,"tick",this.EL),this.i.start())):H6(this,f),this.xe&&!this.Ng&&(4==b?this.g.jn(this):(this.xe=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.kg=3,F6(13)):(this.kg=0,F6(14)),I6(this),J6(this))}}catch(k){this.tc&&P5(this.tc)}finally{}};
g.h.EL=function(){var a=M5(this.tc),b=P5(this.tc);this.Xk<b.length&&(Q6(this),K6(this,a,b),this.xe&&4!=a&&D6(this))};
g.h.dL=function(a){P6((0,g.y)(this.cL,this,a),0)};
g.h.cL=function(a){this.Ng||(Q6(this),H6(this,a),D6(this))};
g.h.fz=function(a){P6((0,g.y)(this.bL,this,a),0)};
g.h.bL=function(a){this.Ng||(I6(this),this.xe=a,this.g.jn(this),this.g.re(4))};
g.h.cancel=function(){this.Ng=!0;I6(this)};
g.h.nL=function(){this.Ui=null;var a=(0,g.D)();0<=a-this.kt?(2!=this.ai&&this.g.re(3),I6(this),this.kg=2,F6(18),J6(this)):O6(this,this.kt-a)};
g.h.getLastError=function(){return this.kg};g.h=U6.prototype;g.h.Vp=null;g.h.Dd=null;g.h.An=!1;g.h.gw=null;g.h.Ul=null;g.h.Lq=null;g.h.Wp=null;g.h.be=null;g.h.xf=-1;g.h.Jj=null;g.h.ej=null;g.h.connect=function(a){this.Wp=a;a=V6(this.g,null,this.Wp);F6(3);this.gw=(0,g.D)();var b=this.g.D;null!=b?(this.Jj=b[0],(this.ej=b[1])?(this.be=1,W6(this)):(this.be=2,Y6(this))):(F5(a,"MODE","init"),this.Dd=new z6(this,void 0,void 0,void 0),this.Dd.Xg=this.Vp,C6(this.Dd,a,!1,null,!0),this.be=0)};
g.h.mC=function(a){if(a)this.be=2,Y6(this);else{F6(4);var b=this.g;b.Je=b.Zf.xf;r7(b,9)}a&&this.re(2)};
g.h.tp=function(a){return this.g.tp(a)};
g.h.abort=function(){this.Dd&&(this.Dd.cancel(),this.Dd=null);this.xf=-1};
g.h.ew=function(){return!1};
g.h.Zy=function(a,b){this.xf=a.Kj;if(0==this.be)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Je=this.xf;r7(c,2);return}this.Jj=c[0];this.ej=c[1]}else c=this.g,c.Je=this.xf,r7(c,2);else if(2==this.be)if(this.An)F6(7),this.Lq=(0,g.D)();else if("11111"==b){if(F6(6),this.An=!0,this.Ul=(0,g.D)(),c=this.Ul-this.gw,!g.Ld||g.nd(10)||500>c)this.xf=200,this.Dd.cancel(),F6(12),X6(this.g,this,!0)}else F6(8),this.Ul=this.Lq=(0,g.D)(),this.An=!1};
g.h.jn=function(){this.xf=this.Dd.Kj;if(this.Dd.xe)0==this.be?this.ej?(this.be=1,W6(this)):(this.be=2,Y6(this)):2==this.be&&((!g.Ld||g.nd(10)?!this.An:200>this.Lq-this.Ul)?(F6(11),X6(this.g,this,!1)):(F6(12),X6(this.g,this,!0)));else{0==this.be?F6(9):2==this.be&&F6(10);var a=this.g;this.Dd.getLastError();a.Je=this.xf;r7(a,2)}};
g.h.Nk=function(){return this.g.Nk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.re=function(a){this.g.re(a)};g.h=Z6.prototype;g.h.rj=null;g.h.zd=null;g.h.Qb=null;g.h.Up=null;g.h.Wl=null;g.h.xu=null;g.h.jm=null;g.h.uk=0;g.h.nH=0;g.h.Tc=null;g.h.fg=null;g.h.kf=null;g.h.Sg=null;g.h.Zf=null;g.h.eo=null;g.h.ki=-1;g.h.Mw=-1;g.h.Je=-1;g.h.Uh=0;g.h.Nh=0;g.h.Og=8;var s7=new g.Sf;g.A($6,g.rf);g.A(a7,g.rf);g.A(b7,g.rf);g.h=Z6.prototype;g.h.connect=function(a,b,c,d,e){F6(0);this.Up=b;this.rj=c||{};d&&g.Ca(e)&&(this.rj.OSID=d,this.rj.OAID=e);this.A?(P6((0,g.y)(this.Ou,this,a),100),h7(this)):this.Ou(a)};
g.h.Ou=function(a){this.Zf=new U6(this);this.Zf.Vp=null;this.Zf.i=this.u;this.Zf.connect(a)};
g.h.ew=function(){return 0==this.g};
g.h.ez=function(a){this.fg=null;m7(this,a)};
g.h.dz=function(){this.kf=null;this.Qb=new z6(this,this.l,"rpc",this.B);this.Qb.Xg=null;this.Qb.Xp=0;var a=this.xu.clone();g.mn(a,"RID","rpc");g.mn(a,"SID",this.l);g.mn(a,"CI",this.eo?"0":"1");g.mn(a,"AID",this.ki);d7(this,a);if(!g.Ld||g.nd(10))g.mn(a,"TYPE","xmlhttp"),C6(this.Qb,a,!0,this.jm,!1);else{g.mn(a,"TYPE","html");var b=this.Qb,c=!!this.jm;b.ai=3;b.jg=E5(a.clone());N6(b,c)}};
g.h.Zy=function(a,b){if(0!=this.g&&(this.Qb==a||this.zd==a))if(this.Je=a.Kj,this.zd==a&&3==this.g)if(7<this.Og){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.kf){if(this.Qb)if(this.Qb.Ei+3E3<this.zd.Ei)i7(this),this.Qb.cancel(),this.Qb=null;else break a;p7(this);F6(19)}}else this.Mw=c[1],0<this.Mw-this.ki&&37500>c[2]&&this.eo&&0==this.Nh&&!this.Sg&&(this.Sg=P6((0,g.y)(this.RH,this),6E3));else r7(this,11)}else b!=Bra.FN.g&&r7(this,11);else if(this.Qb==a&&
i7(this),!g.vb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.ki=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.jm=e[2],e=e[3],null!=e?this.Og=e:this.Og=6,this.g=3,this.Tc&&this.Tc.Iu(),this.xu=V6(this,this.Nk()?this.jm:null,this.Up),n7(this)):"stop"==e[0]&&r7(this,7):3==this.g&&("stop"==e[0]?r7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.Hu(e),this.Nh=0)}}};
g.h.RH=function(){null!=this.Sg&&(this.Sg=null,this.Qb.cancel(),this.Qb=null,p7(this),F6(20))};
g.h.jn=function(a){if(this.Qb==a){i7(this);this.Qb=null;var b=2}else if(this.zd==a)this.zd=null,b=1;else return;this.Je=a.Kj;if(0!=this.g)if(a.xe)1==b?(b=(0,g.D)()-a.Ei,s7.dispatchEvent(new a7(s7,a.sh?a.sh.length:0,b,this.Uh)),g7(this),this.o.length=0):n7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Je)){if(d=1==b)this.zd||this.fg||1==this.g||2<=this.Uh?d=!1:(this.fg=P6((0,g.y)(this.ez,this,a),o7(this,this.Uh)),this.Uh++,d=!0);d=!(d||2==b&&p7(this))}if(d)switch(c){case 1:r7(this,
5);break;case 4:r7(this,10);break;case 3:r7(this,6);break;case 7:r7(this,12);break;default:r7(this,2)}}};
g.h.CC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.mM=function(a){a?F6(2):(F6(1),q7(this,8))};
g.h.tp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.re=function(a){s7.dispatchEvent(new b7(s7,a))};
g.h.Nk=function(){return!(!g.Ld||g.nd(10))};
g.h=t7.prototype;g.h.Iu=function(){};
g.h.Hu=function(){};
g.h.Gu=function(){};
g.h.gp=function(){};
g.h.Iv=function(){return{}};
g.h.isActive=function(){return!0};g.A(u7,g.H);g.h=u7.prototype;g.h.VK=function(){this.Vc=Math.min(3E5,2*this.Vc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.yo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.A(v7,t7);g.h=v7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Gf=function(a){return this.l.Yg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.pf(this.l),w7(this),g.pf(this.i),this.i=null)};
g.h.ea=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new Z6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ki):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):x7(this)&&j7(this.g,c)};
g.h.Iu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)j7(this.g,a[b])}this.N("handlerOpened")};
g.h.Gu=function(a){var b=2==a&&401==this.g.Je;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.gp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.Iv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.dc(a,this.u);return a};
g.h.Hu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),f7(this.g)):this.N("handlerMessage",new nqa(a[0],a[1]))};
g.h.RL=function(){this.i.isActive();var a=this.g,b=0;a.Qb&&b++;a.zd&&b++;0==b&&this.connect(this.u,this.o)};y7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
y7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
y7.prototype.u=function(a){a(Error("request timed out"))};var tqa=(0,g.D)(),D7=null,H7=Array(50),G7=-1,I7=!1;g.A(J7,g.Q);J7.prototype.Jd=function(){return this.g};
J7.prototype.contains=function(a){return!!d6(this.g,a)};
J7.prototype.get=function(a){return a?e6(this.g,a):null};
J7.prototype.info=function(a){F7(this.B,a)};g.A(K7,g.Q);var Cra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=K7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.iB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.bq(this.za),this.za=NaN)};
g.h.T=function(){this.stop();K7.Ha.T.call(this)};
g.h.iB=function(){this.za=NaN;this.g=g.Xq(z7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.JM,this),onError:(0,g.y)(this.IM,this),qd:(0,g.y)(this.KM,this)})};
g.h.JM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new X5(c))};
g.h.IM=function(a){this.g=null;a.status&&404==a.status?this.i>=Cra.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=Cra[this.i],this.za=g.$p((0,g.y)(this.iB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.KM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(M7,J7);g.h=M7.prototype;g.h.start=function(){L7(this)&&this.N("screenChange");!g.zt("yt-remote-lounge-token-expiration")&&xqa(this);g.bq(this.i);this.i=g.$p((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){L7(this);uqa(this,a);N7(this,!1);this.N("screenChange");b(a);a.token||xqa(this)};
g.h.remove=function(a,b){var c=L7(this);wqa(this,a)&&(N7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Zn=function(a,b,c,d){var e=L7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,N7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.bq(this.i);M7.Ha.T.call(this)};
g.h.lD=function(a){L7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}N7(this,!b);b&&F7(this.B,"Missed "+b+" lounge tokens.")};
g.h.kD=function(a){F7(this.B,"Requesting lounge tokens failed: "+a)};g.A(P7,g.Q);g.h=P7.prototype;g.h.start=function(){var a=parseInt(g.zt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?R7(this):(this.o=(0,g.D)()+3E5,g.xt("yt-remote-fast-check-period",this.o),this.ks())};
g.h.isEmpty=function(){return g.Wb(this.g)};
g.h.update=function(){O7("Updating availability on schedule.");var a=this.A(),b=g.Kb(this.g,function(c,d){return c&&!!e6(a,d)},this);
Q7(this,b)};
g.h.T=function(){g.bq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);P7.Ha.T.call(this)};
g.h.ks=function(){g.bq(this.l);this.l=NaN;this.i&&this.i.abort();var a=Aqa(this);if(R5(a)){var b=z7(this.u,"/pairing/get_screen_availability");this.i=A7(this.u,b,{lounge_token:g.Qb(a).join(",")},(0,g.y)(this.zK,this,a),(0,g.y)(this.yK,this))}else Q7(this,{}),R7(this)};
g.h.zK=function(a,b){this.i=null;var c=g.Qb(Aqa(this));if(g.qb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Q7(this,d);R7(this)}else this.Jb("Changing Screen set during request."),this.ks()};
g.h.yK=function(a){this.Jb("Screen availability failed: "+a);this.i=null;R7(this)};
g.h.Jb=function(a){F7("OnlineScreenService",a)};g.A(S7,J7);g.h=S7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Zn=function(a,b,c,d){this.l.contains(a)?this.l.Zn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,F7(this.B,a),d(Error(a)))};
g.h.Jd=function(a){return a?this.g:g.eb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.jB=function(){return(0,g.Xd)(this.Jd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.kB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new K7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.pf(f);d(T7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.pf(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.MM=function(a,b,c,d){g.Xq(z7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new X5(f.screen||{});if(!k.name||Eqa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Eqa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(T7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
qd:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.pf(this.l);g.pf(this.i);S7.Ha.T.call(this)};
g.h.uD=function(){Fqa(this);this.N("screenChange");this.i.update()};
S7.prototype.dispose=S7.prototype.dispose;g.A(V7,g.Q);g.h=V7.prototype;g.h.kn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Md=function(a){this.ea()||(a&&W7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){F7(this.P,a)};
g.h.mB=function(){return null};
g.h.zs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){W7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.zs("");V7.Ha.T.call(this)};g.A(X7,V7);g.h=X7.prototype;g.h.ys=function(a){if(this.g){if(this.g==a)return;W7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Hqa(this)};
g.h.mi=function(a){this.info("launchWithParams no-op for Cast: "+g.Mg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Md()},this),(0,g.y)(function(){this.Md(Error("Failed to stop receiver app."))},this)):this.Md(Error("Stopping cast device witout session."))};
g.h.zs=g.Ga;g.h.T=function(){this.info("disposeInternal");g.bq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;X7.Ha.T.call(this)};
g.h.yL=function(a,b){if(!this.ea())if(b){var c=T5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Mg(c));switch(d){case "mdxSessionStatus":Gqa(this,c.screenId);break;default:W7(this,"Unknown youtube message: "+d)}}else W7(this,"Unable to parse message.")}else W7(this,"No data in message.")};
g.h.Xv=function(a,b,c,d){Dqa(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(W7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.$p((0,g.y)(this.Xv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.mB=function(){return this.g};
g.h.OM=function(a){this.ea()||a||(W7(this,"Cast session died."),this.Md())};g.A(Y7,V7);g.h=Y7.prototype;g.h.ys=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.mi=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ga;g.bq(this.A);this.o?this.o.stop((0,g.y)(this.Md,this,null),(0,g.y)(this.Md,this,"Failed to stop DIAL device.")):this.Md()};
g.h.T=function(){this.g();this.g=g.Ga;g.bq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;Y7.Ha.T.call(this)};
g.h.RM=function(a){this.ea()||a||(W7(this,"DIAL session died."),this.g(),this.g=g.Ga,this.Md())};
g.h.mq=function(a){this.H=c6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,Jqa(this));a(b);Iqa(this)}else this.B=(0,g.y)(function(){g.bq(this.A);this.B=g.Ga;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Jqa(this));a(c);Iqa(this)},this),this.A=g.$p((0,g.y)(function(){this.B()},this),100)};
g.h.RD=function(a,b,c){Dqa(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.kn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.mq(b,c)},this),(0,g.y)(function(d){W7(this,"Failed to get DIAL screen: "+d);
this.mq(b,c)},this))};g.A(Z7,V7);Z7.prototype.stop=function(){this.Md()};
Z7.prototype.ys=g.Ga;Z7.prototype.mi=function(){g.bq(this.g);this.g=NaN;var a=e6(this.F.Jd(),this.i.label);a?this.kn(a):this.Md(Error("No such screen"))};
Z7.prototype.T=function(){g.bq(this.g);this.g=NaN;Z7.Ha.T.call(this)};g.A($7,g.Q);g.h=$7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.bz,this),(0,g.y)(this.iK,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.rI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),qqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.lB,this)),this.l=Lqa(this),chrome.cast.setCustomReceivers(this.l,g.Ga,(0,g.y)(function(f){this.Jb("Failed to set initial custom receivers: "+g.Mg(f))},this)),this.N("yt-remote-cast2-availability-change",b8(this)),b(!0))},this),(0,g.y)(function(f){this.Jb("Failed to initialize API: "+g.Mg(f));
b(!1)},this))};
g.h.aM=function(a,b){a8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)a8("Unsetting old screen status: "+this.g.i.friendlyName),c8(this,null)}if(a&&b){if(!this.g){c=e6(this.i.Jd(),a);if(!c){a8("setConnectedScreenStatus: Unknown screen.");return}var d=Kqa(this,c);d||(a8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ga,(0,g.y)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Mg(e))},this)));
a8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);c8(this,new Z7(this.i,d),!0)}this.g.zs(b)}else a8("setConnectedScreenStatus: no screen.")};
g.h.bM=function(a){this.ea()?this.Jb("Setting connection data on disposed cast v2"):this.g?this.g.mi(a):this.Jb("Setting connection data without a session")};
g.h.QM=function(){this.ea()?this.Jb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),c8(this,null)):a8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.bz,this),(0,g.y)(this.EK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.lB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.x("yt.mdx.remote.debug.handlers_")||[],B7);g.pf(this.g);$7.Ha.T.call(this)};
g.h.Jb=function(a){F7("Controller",a)};
g.h.cz=function(a,b){this.g==a&&(b||c8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.eK=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),a8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)a8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{a8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:c8(this,
new Z7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:c8(this,new Y7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:c8(this,new X7(this.i,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.rI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return a8("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);c8(this,new Y7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.RD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.mq,b))};
g.h.bz=function(a){if(!this.ea()){a8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)a8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),c8(this,new X7(this.i,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=e6(this.i.Jd(),c.label);d&&Y5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(a8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.pf(this.g),this.g=new X7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.cz,this,this.g)),this.g.mi(null));this.g.ys(a)}}};
g.h.PM=function(){return this.g?this.g.mB():null};
g.h.EK=function(a){this.ea()||(this.Jb("Failed to estabilish a session: "+g.Mg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&c8(this,null))};
g.h.iK=function(a){a8("Receiver availability updated: "+a);if(!this.ea()){var b=b8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;b8(this)!=b&&this.N("yt-remote-cast2-availability-change",b8(this))}};
g.h.lB=function(){this.ea()||(this.l=Lqa(this),a8("Updating custom receivers: "+g.Mg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ga,(0,g.y)(function(){this.Jb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",b8(this)))};
$7.prototype.setLaunchParams=$7.prototype.bM;$7.prototype.setConnectedScreenStatus=$7.prototype.aM;$7.prototype.stopSession=$7.prototype.QM;$7.prototype.getCastSession=$7.prototype.PM;$7.prototype.requestSession=$7.prototype.requestSession;$7.prototype.init=$7.prototype.init;$7.prototype.dispose=$7.prototype.dispose;var i8=[];n8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";o8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Le=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
n8.prototype.isAdPlaying=function(){return 1081==this.playerState};
n8.prototype.getDuration=function(){return this.u?this.D+p8(this):this.D};
n8.prototype.clone=function(){return new n8(t8(this))};g.A(v8,g.Q);g.h=v8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ga,B8(this,"play")):A8(this,"play"),z8(this,1,r8(w8(this))),this.N("remotePlayerChange")):x8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ga,B8(this,"pause")):A8(this,"pause"),z8(this,2,r8(w8(this))),this.N("remotePlayerChange")):x8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=w8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ga,B8(this,"seekTo",{newTime:a}))}else A8(this,"seekTo",{newTime:a});z8(this,3,a);this.N("remotePlayerChange")}else x8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ga,B8(this,"stopVideo")):A8(this,"stopVideo");var a=w8(this);a.index=-1;a.videoId="";o8(a);y8(this,a);this.N("remotePlayerChange")}else x8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=w8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){F7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){F7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);A8(this,"setVolume",e)}c.muted=b;c.volume=a;y8(this,c)}else x8(this,g.Qa(this.setVolume,a,b))};
g.h.mA=function(a,b){if(1==this.g){var c=w8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Mg(b.style),g.dc(d,c.g));A8(this,"setSubtitlesTrack",d);y8(this,c)}else x8(this,g.Qa(this.mA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();A8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=w8(this);d.audioTrackId=c;y8(this,d)}else x8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=w8(this);c=c||0;var m={videoId:a,currentIndex:c};s8(l,a,c);g.Ca(b)&&(q8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Mg(k));A8(this,"setPlaylist",m);d||y8(this,l)};
g.h.vn=function(a,b){if(1==this.g){if(a&&b){var c=w8(this);s8(c,a,b);y8(this,c)}A8(this,"previous")}else x8(this,g.Qa(this.vn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=w8(this);s8(c,a,b);y8(this,c)}A8(this,"next")}else x8(this,g.Qa(this.nextVideo,a,b))};
g.h.hv=function(){1==this.g?A8(this,"dismissAutoplay"):x8(this,this.hv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}v8.Ha.dispose.call(this)};
g.h.T=function(){Yqa(this);this.o=null;this.u.clear();u8(this,null);v8.Ha.T.call(this)};
g.h.nt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.bK=function(a,b){this.N(a,b)};
g.h.XH=function(a){if(!a)this.xk(null),u8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=w8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)F7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,y8(this,b)}};
g.h.xk=function(a){F7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Zqa(this),this.N("remotePlayerChange")};
g.h.WH=function(a){a?(Zqa(this),this.N("remotePlayerChange")):this.xk(null)};
g.h.Rs=function(){A8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.jI=function(){var a=Vqa();a&&u8(this,a)};
g.h.Jb=function(a){F7("CP",a)};g.A(C8,g.Q);g.h=C8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;q8(this.Pa,m);this.o="UNSUPPORTED";D8("Connecting with setPlaylist and params: "+g.Mg(l));this.g.connect({method:"setPlaylist",
params:g.Mg(l)},a,k6())}else D8("Connecting without params"),this.g.connect({},a,k6());ara(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),E8(this,3));C8.Ha.dispose.call(this)};
g.h.T=function(){F8(this);H8(this);G8(this);g.bq(this.F);this.F=NaN;g.bq(this.H);this.H=NaN;this.l=null;g.es(this.O);this.O.length=0;this.g.dispose();C8.Ha.T.call(this);this.o=this.B=this.i=this.Pa=this.g=null};
g.h.eD=function(){this.A(2)};
g.h.bI=function(){D8("Channel opened");this.M&&(this.M=!1,G8(this),this.P=g.$p((0,g.y)(function(){D8("Timing out waiting for a screen.");this.A(1)},this),15E3));
hqa(oqa(this.g),this.V)};
g.h.YH=function(){D8("Channel closed");isNaN(this.u)?n6(!0):n6();this.dispose()};
g.h.ZH=function(a){n6();isNaN(this.D())?(D8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,D8("Channel error: "+a+" with reconnection in "+this.D()+" ms"),E8(this,2))};
g.h.aI=function(a){a.params?D8("Received: action="+a.action+", params="+g.Mg(a.params)):D8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=T5(a.params.devices);this.i=(0,g.G)(a,function(c){return new W5(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
dra(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
dra(this,!1);break;case "remoteConnected":var b=new W5(T5(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||Wpa(this.i,b);
break;case "remoteDisconnected":b=new W5(T5(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":fra(this,a);break;case "nowPlaying":hra(this,a);break;case "onStateChange":gra(this,a);break;case "onAdStateChange":ira(this,a);break;case "onVolumeChanged":jra(this,a);break;case "onSubtitlesTrackChanged":era(this,a);break;case "nowAutoplaying":kra(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.N("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":lra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:D8("Unrecognized action: "+a.action)}};
g.h.OL=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&I8(this,"getNowPlaying")}};
C8.prototype.subscribe=C8.prototype.subscribe;C8.prototype.unsubscribeByKey=C8.prototype.Gf;C8.prototype.ca=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?x7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
C8.prototype.getProxyState=C8.prototype.ca;C8.prototype.A=function(a){D8("Disconnecting with "+a);F8(this);this.N("beforeDisconnect",a);1==a&&n6();w7(this.g,a);this.dispose()};
C8.prototype.disconnect=C8.prototype.A;C8.prototype.X=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),s8(a,this.l,a.index));return t8(a)};
C8.prototype.getPlayerContextData=C8.prototype.X;
C8.prototype.ka=function(a){var b=new n8(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.bq(this.F),this.F=g.$p((0,g.y)(this.OL,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&r8(this.Pa)==r8(b)&&g.Mg(this.Pa.g)==g.Mg(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
C8.prototype.setPlayerContextData=C8.prototype.ka;C8.prototype.R=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
C8.prototype.getOtherConnectedRemoteId=C8.prototype.R;C8.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
C8.prototype.getReconnectTimeout=C8.prototype.D;C8.prototype.aa=function(){return this.o||"UNSUPPORTED"};
C8.prototype.getAutoplayMode=C8.prototype.aa;C8.prototype.Z=function(){return this.B||""};
C8.prototype.getAutoplayVideoId=C8.prototype.Z;C8.prototype.va=function(){if(!isNaN(this.D())){var a=this.g.i;g.zo(a.g);a.start()}};
C8.prototype.reconnect=C8.prototype.va;C8.prototype.ia=function(a,b){I8(this,a,b);cra(this)};
C8.prototype.sendMessage=C8.prototype.ia;g.A(J8,J7);g.h=J8.prototype;g.h.Jd=function(a){return this.Hc.$_gs(a)};
g.h.contains=function(a){return!!this.Hc.$_c(a)};
g.h.get=function(a){return this.Hc.$_g(a)};
g.h.start=function(){this.Hc.$_st()};
g.h.add=function(a,b,c){this.Hc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Hc.$_r(a,b,c)};
g.h.Zn=function(a,b,c,d){this.Hc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Hc.$_ubk(this.i[a]);this.i.length=0;this.Hc=null;J8.Ha.T.call(this)};
g.h.LM=function(){this.N("screenChange")};
g.h.FJ=function(){this.N("onlineScreenChange")};
S7.prototype.$_st=S7.prototype.start;S7.prototype.$_gspc=S7.prototype.MM;S7.prototype.$_gsppc=S7.prototype.kB;S7.prototype.$_c=S7.prototype.contains;S7.prototype.$_g=S7.prototype.get;S7.prototype.$_a=S7.prototype.add;S7.prototype.$_un=S7.prototype.Zn;S7.prototype.$_r=S7.prototype.remove;S7.prototype.$_gs=S7.prototype.Jd;S7.prototype.$_gos=S7.prototype.jB;S7.prototype.$_s=S7.prototype.subscribe;S7.prototype.$_ubk=S7.prototype.Gf;var K8=null,L8=null,$8=null,P8=[];g.t(a9,g.H);g.h=a9.prototype;
g.h.T=function(){g.H.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Yy,this);this.g.unsubscribe("remotePlayerChange",this.zk,this);this.g.unsubscribe("remoteQueueChange",this.ln,this);this.g.unsubscribe("autoplayUpNext",this.Cy,this);this.g.unsubscribe("previousNextChange",this.Vy,this);this.g.unsubscribe("nowAutoplaying",this.Ry,this);this.g.unsubscribe("autoplayDismissed",this.By,this);this.g=this.u=null};
g.h.Bx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(d9(this)){if(!w8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==w8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Gj(c[0],c[1]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();f9(this,0==c?void 0:c);break;case "control_seek":f9(this,c[0]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.VH=function(a){this.I.aD(a)};
g.h.vM=function(a){this.Bx("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.yA=function(){var a=this.i.getOption("captions","track");g.Wb(a)||e9(this,a)};
g.h.Ny=function(a){if(d9(this)){this.g.unsubscribe("remotePlayerChange",this.zk,this);var b=Math.round(a.volume);a=!!a.muted;var c=w8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.zk,this)}};
g.h.WI=function(){g.Wb(this.B)||xra(this,this.B);this.D=!1};
g.h.Yy=function(a,b){this.A.stop();2==b&&this.xA()};
g.h.zk=function(){if(d9(this)){this.o.stop();var a=w8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Bm=1;break;case 1082:case 1083:this.u.Bm=0;break;default:this.u.Bm=-1}switch(a.playerState){case 1081:case 1:c9(this,new g.AC(8));this.wA();break;case 1085:case 3:c9(this,new g.AC(9));break;case 1083:case 0:c9(this,new g.AC(2));this.H.stop();b9(this,this.i.getVideoData().lengthSeconds);break;case 1084:c9(this,new g.AC(4));break;case 2:c9(this,new g.AC(4));b9(this,r8(a));
break;case -1:c9(this,new g.AC(64));break;case -1E3:c9(this,new g.AC(128,{errorCode:"mdx.remoteerror",message:"Video n\u00e0y kh\u00f4ng kh\u1ea3 d\u1ee5ng \u0111\u1ec3 ph\u00e1t l\u1ea1i t\u1eeb xa."}))}a=w8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,xra(this,a));a=w8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.WA()}else wra(this)};
g.h.Vy=function(){this.i.N("mdxpreviousnextchange")};
g.h.ln=function(){d9(this)||wra(this)};
g.h.lC=function(){this.g.hv()};
g.h.Cy=function(a){a&&(a=g.Xq("/watch_queue_ajax",{method:"GET",Ec:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.gL,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.gL=function(a,b){var c=new g.lB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Ry=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.By=function(){this.i.N("mdxautoplaycanceled")};
g.h.BF=function(a,b){-1==w8(this.g).playerState?f9(this,a):b&&this.g.seekTo(a)};
g.h.WA=function(){if(d9(this)){var a=w8(this.g);this.l.Ma(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Ny)}};
g.h.wA=function(){this.o.stop();if(!this.g.ea()){var a=w8(this.g);1==a.playerState&&c9(this,new g.AC(8));b9(this,r8(a));this.o.start()}};
g.h.xA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(g9,g.W);g9.prototype.u=function(a){zra(this,a.state)};g.t(h9,g.ZT);h9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.sb(a,this.A,this),g.$T(this,(0,g.G)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.qe(this.A(a)),this.enable(!0)):this.enable(!1)};
h9.prototype.A=function(a){return a.key};
h9.prototype.pe=function(a){return"cast-selector-receiver"==a?"Truy\u1ec1n...":this.F[a].name};
h9.prototype.Jc=function(a){g.ZT.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(i9,g.TK);g.h=i9.prototype;g.h.create=function(){qra(g.cz(g.X(this.player)));this.u.push(g.gq("yt-remote-before-disconnect",this.SH,this));this.u.push(g.gq("yt-remote-connection-change",this.jK,this));this.u.push(g.gq("yt-remote-receiver-availability-change",this.Wy,this));this.u.push(g.gq("yt-remote-auto-connect",this.hK,this));this.u.push(g.gq("yt-remote-receiver-resumed",this.gK,this));this.Wy()};
g.h.load=function(){this.player.cancelPlayback();g.TK.prototype.load.call(this);this.o=new a9(this,this.player,this.g);var a=(a=vra())?a.currentTime:0;var b=Z8()?new v8(U8(),void 0):null;0==a&&b&&(a=r8(w8(b)));0!=a&&this.rd(a);yra(this,this.fk,this.fk);g.YX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.qf(this.o,this.g);this.g=this.o=null;g.TK.prototype.unload.call(this);g.YX(this.player.app,5)};
g.h.T=function(){g.hq(this.u);g.TK.prototype.T.call(this)};
g.h.We=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.Bx.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Bm};
g.h.WC=function(){return this.loaded?this.o.suggestion:null};
g.h.Le=function(){return this.g?w8(this.g).Le:!1};
g.h.hasNext=function(){return this.g?w8(this.g).hasNext:!1};
g.h.rd=function(a,b){this.D=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=w8(this.g),b=this.player.getVideoData();return{allowSeeking:g.R(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ec():!a.isAdPlaying()&&this.player.ec(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+p8(a):a.l,isAtLiveHead:1>=(a.u?a.i+p8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+p8(a):a.i,seekableStart:0<a.o?a.o+
p8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.vn=function(){this.g&&this.g.vn()};
g.h.SH=function(a){1==a&&(this.B=this.g?w8(this.g):null)};
g.h.jK=function(){var a=Z8()?new v8(U8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.pf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,r8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Wy=function(){this.A=[this.i].concat(sra());var a=V8()||this.i;j9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.hK=function(){var a=V8();j9(this,a)};
g.h.gK=function(){this.l=V8()};
g.h.Zb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l8():j9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&l8(),!0):!1}};
g.h.Rs=function(){this.g.Rs()};
g.h.Ib=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.oV.remote=i9;})(_yt_player);
